const artistData = [
  {
    name: "VAN GOGH",
    imgUrl: "/images/artist_1.svg",
    works: [
      {
        name: "THE STORY OF THE EYES",
        artist: "Van Goch",
        imgUrl: "/images/artist_1.svg",
        type: "Glossed art print",
        size: "70 x 45 cm",
        price: "150",
        id: 1.1,
        routeName: "work1",
      },
      {
        name: "THE STORY OF THE EYES",
        artist: "Van Goch",
        imgUrl: "/images/artist_4.jpg",
        type: "Glossed art print",
        size: "70 x 45 cm",
        price: "150",
        id: 1.2,
        routeName: "work2",
      },
      {
        name: "THE STORY OF THE EYES",
        artist: "Van Goch",
        imgUrl: "/images/artist_3.jpg",
        type: "Glossed art print",
        size: "70 x 45 cm",
        price: "150",
        id: 1.3,
        routeName: "work3",
      },
      {
        name: "THE STORY OF THE EYES",
        artist: "Van Goch",
        imgUrl: "/images/artist_2.svg",
        type: "Glossed art print",
        size: "70 x 45 cm",
        price: "150",
        id: 1.4,
        routeName: "work4",
      },
    ],
    id: 1,
  },
  {
    name: "JACKSON POLLOCK",
    imgUrl: "/images/artist_2.svg",
    works: [
      {
        name: "THE STORY OF THE EYES",
        artist: "Jackson Pollock",
        imgUrl: "/images/artist_4.jpg",
        type: "Glossed art print",
        size: "70 x 45 cm",
        price: "150",
        id: 2.1,
        routeName: "work1",
      },
      {
        name: "THE STORY OF THE EYES",
        artist: "Jackson Pollock",
        imgUrl: "/images/artist_2.svg",
        type: "Glossed art print",
        size: "70 x 45 cm",
        price: "150",
        id: 2.2,
        routeName: "work2",
      },
      {
        name: "THE STORY OF THE EYES",
        artist: "Jackson Pollock",
        imgUrl: "/images/artist_3.jpg",
        type: "Glossed art print",
        size: "70 x 45 cm",
        price: "150",
        id: 2.3,
        routeName: "work3",
      },
      {
        name: "THE STORY OF THE EYES",
        artist: "Jackson Pollock",
        imgUrl: "/images/artist_1.svg",
        type: "Glossed art print",
        size: "70 x 45 cm",
        price: "150",
        id: 2.4,
        routeName: "work4",
      },
    ],
    id: 2,
  },
  {
    name: "ARTISTGOD",
    imgUrl: "/images/artist_3.jpg",
    works: [
      {
        name: "THE STORY OF THE EYES",
        artist: "ARTISTGOD",
        imgUrl: "/images/artist_2.svg",
        type: "Glossed art print",
        size: "70 x 45 cm",
        price: "150",
        id: 3.1,
        routeName: "work1",
      },
      {
        name: "THE STORY OF THE EYES",
        artist: "ARTISTGOD",
        imgUrl: "/images/artist_1.svg",
        type: "Glossed art print",
        size: "70 x 45 cm",
        price: "150",
        id: 3.2,
        routeName: "work2",
      },
      {
        name: "THE STORY OF THE EYES",
        artist: "ARTISTGOD",
        imgUrl: "/images/artist_3.jpg",
        type: "Glossed art print",
        size: "70 x 45 cm",
        price: "150",
        id: 3.3,
        routeName: "work3",
      },
      {
        name: "THE STORY OF THE EYES",
        artist: "ARTISTGOD",
        imgUrl: "/images/artist_4.jpg",
        type: "Glossed art print",
        size: "70 x 45 cm",
        price: "150",
        id: 3.4,
        routeName: "work4",
      },
    ],
    id: 3,
  },
  {
    name: "RON LAWSON",
    imgUrl: "/images/artist_4.jpg",
    works: [
      {
        name: "THE STORY OF THE EYES",
        artist: "Ron Lawson",
        imgUrl: "/images/artist_4.jpg",
        type: "Glossed art print",
        size: "70 x 45 cm",
        price: "150",
        id: 4.1,
        routeName: "work1",
      },
      {
        name: "THE STORY OF THE EYES",
        artist: "Ron Lawson",
        imgUrl: "/images/artist_3.jpg",
        type: "Glossed art print",
        size: "70 x 45 cm",
        price: "150",
        id: 4.2,
        routeName: "work2",
      },
      {
        name: "THE STORY OF THE EYES",
        artist: "Ron Lawson",
        imgUrl: "/images/artist_2.svg",
        type: "Glossed art print",
        size: "70 x 45 cm",
        price: "150",
        id: 4.3,
        routeName: "work3",
      },
      {
        name: "THE STORY OF THE EYES",
        artist: "Ron Lawson",
        imgUrl: "/images/artist_1.svg",
        type: "Glossed art print",
        size: "70 x 45 cm",
        price: "150",
        id: 4.4,
        routeName: "work4",
      },
    ],
    id: 4,
  },
  {
    name: "VAN GOGH",
    imgUrl: "/images/artist_1.svg",
    works: [
      {
        name: "THE STORY OF THE EYES",
        artist: "Van Goch",
        imgUrl: "/images/artist_1.svg",
        type: "Glossed art print",
        size: "70 x 45 cm",
        price: "150",
        id: 5.1,
        routeName: "work1",
      },
      {
        name: "THE STORY OF THE EYES",
        artist: "Van Goch",
        imgUrl: "/images/artist_3.jpg",
        type: "Glossed art print",
        size: "70 x 45 cm",
        price: "150",
        id: 5.2,
        routeName: "work2",
      },
      {
        name: "THE STORY OF THE EYES",
        artist: "Van Goch",
        imgUrl: "/images/artist_4.jpg",
        type: "Glossed art print",
        size: "70 x 45 cm",
        price: "150",
        id: 5.3,
        routeName: "work3",
      },
      {
        name: "THE STORY OF THE EYES",
        artist: "Van Goch",
        imgUrl: "/images/artist_2.svg",
        type: "Glossed art print",
        size: "70 x 45 cm",
        price: "150",
        id: 5.4,
        routeName: "work4",
      },
    ],
    id: 5,
  },
  {
    name: "JACKSON POLLOCK",
    imgUrl: "/images/artist_2.svg",
    works: [
      {
        name: "THE STORY OF THE EYES",
        artist: "Jackson Pollock",
        imgUrl: "/images/artist_1.svg",
        type: "Glossed art print",
        size: "70 x 45 cm",
        price: "150",
        id: 6.1,
        routeName: "work1",
      },
      {
        name: "THE STORY OF THE EYES",
        artist: "Jackson Pollock",
        imgUrl: "/images/artist_2.svg",
        type: "Glossed art print",
        size: "70 x 45 cm",
        price: "150",
        id: 6.2,
        routeName: "work2",
      },
      {
        name: "THE STORY OF THE EYES",
        artist: "Jackson Pollock",
        imgUrl: "/images/artist_3.jpg",
        type: "Glossed art print",
        size: "70 x 45 cm",
        price: "150",
        id: 6.3,
        routeName: "work3",
      },
      {
        name: "THE STORY OF THE EYES",
        artist: "Jackson Pollock",
        imgUrl: "/images/artist_4.jpg",
        type: "Glossed art print",
        size: "70 x 45 cm",
        price: "150",
        id: 6.4,
        routeName: "work4",
      },
    ],
    id: 6,
  },
  {
    name: "ARTISTGOD",
    imgUrl: "/images/artist_3.jpg",
    works: [
      {
        name: "THE STORY OF THE EYES",
        artist: "ARTISTGOD",
        imgUrl: "/images/artist_4.jpg",
        type: "Glossed art print",
        size: "70 x 45 cm",
        price: "150",
        id: 7.1,
        routeName: "work1",
      },
      {
        name: "THE STORY OF THE EYES",
        artist: "ARTISTGOD",
        imgUrl: "/images/artist_1.svg",
        type: "Glossed art print",
        size: "70 x 45 cm",
        price: "150",
        id: 7.2,
        routeName: "work2",
      },
      {
        name: "THE STORY OF THE EYES",
        artist: "ARTISTGOD",
        imgUrl: "/images/artist_2.svg",
        type: "Glossed art print",
        size: "70 x 45 cm",
        price: "150",
        id: 7.3,
        routeName: "work3",
      },
      {
        name: "THE STORY OF THE EYES",
        artist: "ARTISTGOD",
        imgUrl: "/images/artist_3.jpg",
        type: "Glossed art print",
        size: "70 x 45 cm",
        price: "150",
        id: 7.4,
        routeName: "work4",
      },
    ],
    id: 7,
  },
  {
    name: "RON LAWSON",
    imgUrl: "/images/artist_4.jpg",
    works: [
      {
        name: "THE STORY OF THE EYES",
        artist: "Ron Lawson",
        imgUrl: "/images/artist_2.svg",
        type: "Glossed art print",
        size: "70 x 45 cm",
        price: "150",
        id: 8.1,
        routeName: "work1",
      },
      {
        name: "THE STORY OF THE EYES",
        artist: "Ron Lawson",
        imgUrl: "/images/artist_1.svg",
        type: "Glossed art print",
        size: "70 x 45 cm",
        price: "150",
        id: 8.2,
        routeName: "work2",
      },
      {
        name: "THE STORY OF THE EYES",
        artist: "Ron Lawson",
        imgUrl: "/images/artist_3.jpg",
        type: "Glossed art print",
        size: "70 x 45 cm",
        price: "150",
        id: 8.3,
        routeName: "work3",
      },
      {
        name: "THE STORY OF THE EYES",
        artist: "Ron Lawson",
        imgUrl: "/images/artist_4.jpg",
        type: "Glossed art print",
        size: "70 x 45 cm",
        price: "150",
        id: 8.4,
        routeName: "work4",
      },
    ],
    id: 8,
  },
  {
    name: "VAN GOGH",
    imgUrl: "/images/artist_1.svg",
    works: [
      {
        name: "THE STORY OF THE EYES",
        artist: "Van Goch",
        imgUrl: "/images/artist_1.svg",
        type: "Glossed art print",
        size: "70 x 45 cm",
        price: "150",
        id: 9.1,
        routeName: "work1",
      },
      {
        name: "THE STORY OF THE EYES",
        artist: "Van Goch",
        imgUrl: "/images/artist_2.svg",
        type: "Glossed art print",
        size: "70 x 45 cm",
        price: "150",
        id: 9.2,
        routeName: "work2",
      },
      {
        name: "THE STORY OF THE EYES",
        artist: "Van Goch",
        imgUrl: "/images/artist_3.jpg",
        type: "Glossed art print",
        size: "70 x 45 cm",
        price: "150",
        id: 9.3,
        routeName: "work3",
      },
      {
        name: "THE STORY OF THE EYES",
        artist: "Van Goch",
        imgUrl: "/images/artist_4.jpg",
        type: "Glossed art print",
        size: "70 x 45 cm",
        price: "150",
        id: 9.4,
        routeName: "work4",
      },
    ],
    id: 9,
  },
  {
    name: "JACKSON POLLOCK",
    imgUrl: "/images/artist_2.svg",
    works: [
      {
        name: "THE STORY OF THE EYES",
        artist: "Jackson Pollock",
        imgUrl: "/images/artist_4.jpg",
        type: "Glossed art print",
        size: "70 x 45 cm",
        price: "150",
        id: 10.1,
        routeName: "work1",
      },
      {
        name: "THE STORY OF THE EYES",
        artist: "Jackson Pollock",
        imgUrl: "/images/artist_3.jpg",
        type: "Glossed art print",
        size: "70 x 45 cm",
        price: "150",
        id: 10.2,
        routeName: "work2",
      },
      {
        name: "THE STORY OF THE EYES",
        artist: "Jackson Pollock",
        imgUrl: "/images/artist_1.svg",
        type: "Glossed art print",
        size: "70 x 45 cm",
        price: "150",
        id: 10.3,
        routeName: "work3",
      },
      {
        name: "THE STORY OF THE EYES",
        artist: "Jackson Pollock",
        imgUrl: "/images/artist_2.svg",
        type: "Glossed art print",
        size: "70 x 45 cm",
        price: "150",
        id: 10.4,
        routeName: "work4",
      },
    ],
    id: 10,
  },
  {
    name: "ARTISTGOD",
    imgUrl: "/images/artist_3.jpg",
    works: [
      {
        name: "THE STORY OF THE EYES",
        artist: "ARTISTGOD",
        imgUrl: "/images/artist_4.jpg",
        type: "Glossed art print",
        size: "70 x 45 cm",
        price: "150",
        id: 11.1,
        routeName: "work1",
      },
      {
        name: "THE STORY OF THE EYES",
        artist: "ARTISTGOD",
        imgUrl: "/images/artist_3.jpg",
        type: "Glossed art print",
        size: "70 x 45 cm",
        price: "150",
        id: 11.2,
        routeName: "work2",
      },
      {
        name: "THE STORY OF THE EYES",
        artist: "ARTISTGOD",
        imgUrl: "/images/artist_2.svg",
        type: "Glossed art print",
        size: "70 x 45 cm",
        price: "150",
        id: 11.3,
        routeName: "work3",
      },
      {
        name: "THE STORY OF THE EYES",
        artist: "ARTISTGOD",
        imgUrl: "/images/artist_1.svg",
        type: "Glossed art print",
        size: "70 x 45 cm",
        price: "150",
        id: 11.4,
        routeName: "work4",
      },
    ],
    id: 11,
  },
  {
    name: "RON LAWSON",
    imgUrl: "/images/artist_4.jpg",
    works: [
      {
        name: "THE STORY OF THE EYES",
        artist: "Ron Lawson",
        imgUrl: "/images/artist_3.jpg",
        type: "Glossed art print",
        size: "70 x 45 cm",
        price: "150",
        id: 12.1,
        routeName: "work1",
      },
      {
        name: "THE STORY OF THE EYES",
        artist: "Ron Lawson",
        imgUrl: "/images/artist_2.svg",
        type: "Glossed art print",
        size: "70 x 45 cm",
        price: "150",
        id: 12.2,
        routeName: "work2",
      },
      {
        name: "THE STORY OF THE EYES",
        artist: "Ron Lawson",
        imgUrl: "/images/artist_4.jpg",
        type: "Glossed art print",
        size: "70 x 45 cm",
        price: "150",
        id: 12.3,
        routeName: "work3",
      },
      {
        name: "THE STORY OF THE EYES",
        artist: "Ron Lawson",
        imgUrl: "/images/artist_1.svg",
        type: "Glossed art print",
        size: "70 x 45 cm",
        price: "150",
        id: 12.4,
        routeName: "work4",
      },
    ],
    id: 12,
  },
  {
    name: "VAN GOGH",
    imgUrl: "/images/artist_1.svg",
    works: [
      {
        name: "THE STORY OF THE EYES",
        artist: "Van Goch",
        imgUrl: "/images/artist_3.jpg",
        type: "Glossed art print",
        size: "70 x 45 cm",
        price: "150",
        id: 13.1,
        routeName: "work1",
      },
      {
        name: "THE STORY OF THE EYES",
        artist: "Van Goch",
        imgUrl: "/images/artist_2.svg",
        type: "Glossed art print",
        size: "70 x 45 cm",
        price: "150",
        id: 13.2,
        routeName: "work2",
      },
      {
        name: "THE STORY OF THE EYES",
        artist: "Van Goch",
        imgUrl: "/images/artist_1.svg",
        type: "Glossed art print",
        size: "70 x 45 cm",
        price: "150",
        id: 13.3,
        routeName: "work3",
      },
      {
        name: "THE STORY OF THE EYES",
        artist: "Van Goch",
        imgUrl: "/images/artist_4.jpg",
        type: "Glossed art print",
        size: "70 x 45 cm",
        price: "150",
        id: 13.4,
        routeName: "work4",
      },
    ],
    id: 13,
  },
  {
    name: "JACKSON POLLOCK",
    imgUrl: "/images/artist_2.svg",
    works: [
      {
        name: "THE STORY OF THE EYES",
        artist: "Jackson Pollock",
        imgUrl: "/images/artist_2.svg",
        type: "Glossed art print",
        size: "70 x 45 cm",
        price: "150",
        id: 14.1,
        routeName: "work1",
      },
      {
        name: "THE STORY OF THE EYES",
        artist: "Jackson Pollock",
        imgUrl: "/images/artist_4.jpg",
        type: "Glossed art print",
        size: "70 x 45 cm",
        price: "150",
        id: 14.2,
        routeName: "work2",
      },
      {
        name: "THE STORY OF THE EYES",
        artist: "Jackson Pollock",
        imgUrl: "/images/artist_1.svg",
        type: "Glossed art print",
        size: "70 x 45 cm",
        price: "150",
        id: 14.3,
        routeName: "work3",
      },
      {
        name: "THE STORY OF THE EYES",
        artist: "Jackson Pollock",
        imgUrl: "/images/artist_3.jpg",
        type: "Glossed art print",
        size: "70 x 45 cm",
        price: "150",
        id: 14.4,
        routeName: "work4",
      },
    ],
    id: 14,
  },
  {
    name: "ARTISTGOD",
    imgUrl: "/images/artist_3.jpg",
    works: [
      {
        name: "THE STORY OF THE EYES",
        artist: "ARTISTGOD",
        imgUrl: "/images/artist_2.svg",
        type: "Glossed art print",
        size: "70 x 45 cm",
        price: "150",
        id: 15.1,
        routeName: "work1",
      },
      {
        name: "THE STORY OF THE EYES",
        artist: "ARTISTGOD",
        imgUrl: "/images/artist_1.svg",
        type: "Glossed art print",
        size: "70 x 45 cm",
        price: "150",
        id: 15.2,
        routeName: "work2",
      },
      {
        name: "THE STORY OF THE EYES",
        artist: "ARTISTGOD",
        imgUrl: "/images/artist_4.jpg",
        type: "Glossed art print",
        size: "70 x 45 cm",
        price: "150",
        id: 15.3,
        routeName: "work3",
      },
      {
        name: "THE STORY OF THE EYES",
        artist: "ARTISTGOD",
        imgUrl: "/images/artist_3.jpg",
        type: "Glossed art print",
        size: "70 x 45 cm",
        price: "150",
        id: 15.4,
        routeName: "work4",
      },
    ],
    id: 15,
  },
  {
    name: "RON LAWSON",
    imgUrl: "/images/artist_4.jpg",
    works: [
      {
        name: "THE STORY OF THE EYES",
        artist: "Ron Lawson",
        imgUrl: "/images/artist_1.svg",
        type: "Glossed art print",
        size: "70 x 45 cm",
        price: "150",
        id: 16.1,
        routeName: "work1",
      },
      {
        name: "THE STORY OF THE EYES",
        artist: "Ron Lawson",
        imgUrl: "/images/artist_2.svg",
        type: "Glossed art print",
        size: "70 x 45 cm",
        price: "150",
        id: 16.2,
        routeName: "work2",
      },
      {
        name: "THE STORY OF THE EYES",
        artist: "Ron Lawson",
        imgUrl: "/images/artist_3.jpg",
        type: "Glossed art print",
        size: "70 x 45 cm",
        price: "150",
        id: 16.3,
        routeName: "work3",
      },
      {
        name: "THE STORY OF THE EYES",
        artist: "Ron Lawson",
        imgUrl: "/images/artist_4.jpg",
        type: "Glossed art print",
        size: "70 x 45 cm",
        price: "150",
        id: 16.4,
        routeName: "work4",
      },
    ],
    id: 16,
  },
];

export default artistData;
